--EXCLUIR USER
--DROP USER "GERENCIADOR_FINANCEIRO" CASCADE;

-- USER SQL
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER "GERENCIADOR_FINANCEIRO" IDENTIFIED BY "GF693618" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;

-- ROLES
GRANT CONNECT TO GERENCIADOR_FINANCEIRO;
GRANT DBA TO GERENCIADOR_FINANCEIRO;            -- A T E N Ç Ã O: ACESSO PROVISÓRIO DE DBA ATÉ QUE SEJAM FEITAS TODOS OS GRANT CORRETOS

-- SYSTEM PRIVILEGES
GRANT CREATE SESSION, ALTER SESSION TO GERENCIADOR_FINANCEIRO;
GRANT CREATE TABLE TO GERENCIADOR_FINANCEIRO;

-- QUOTAS
GRANT UNLIMITED TABLESPACE TO GERENCIADOR_FINANCEIRO;
ALTER USER GERENCIADOR_FINANCEIRO QUOTA UNLIMITED ON USERS;